# bamboo-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bamboo-shared-home
  namespace: bamboo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
